#The-Gate-v0.1.8-2
#Note:
#You can edit all the text to you harts content :D
#Do not give two guis the same name, it confuses the plugin
#You can add elements to lists or change there order
#{} marks variables the brackets are replaced with the contents of the variables you can if you want remove the variables or change there order

GateDisplayText:
  - '&6Address: &3{ADDRESS}'
  - '&6Monde: &3{WORLD}'
  - '&6Nom: &3{GATENAME}'
  - '&6Reseau(x): &3{NETWORK1} {NETWORK2}'
  - '&6Createur: &3{OWNER}'
  - '&6Info: &3{DESCRIPTION}'

GUIS:
  AbydosGUI:
    GUIName: '&5Abydos_Cartouche'
    Items:
      GateObjects:
        Lore: 
          - 'Nom: {GATENAME}'
          - 'Monde: {WORLD}'
          - 'Localasation: '
          - 'X: {X}'
          - 'Y: {Y}'
          - 'Z: {Z}'
          - 'Res: {NETWORK}'
          - 'Createur: {OWNER}'
          - '{DESCRIPTION}'
      NextPage: 'Page Suivante'
      PreviousPage: 'Page Précédente'
  
  AddressAssignGUI:
    GUIName: '&5Address_Assign_GUI'
    Items:
      Address-not-allowed: 'Addresse Interdite'
      Clear: 'CLEAR'
      Randomize: 'Aléatoire'
      CreateGate: 'Crée La Porte'
  
  DHD_GUI:
    GUIName: '&5DHD &3{ADDRESS}'
    Items:
      Dial:
        Name: 'Appeler'
        Lore: 'Activer La Porte'
      Clear_Dial:
        Name: 'CLEAR DIAL'
        Lore: 'Clears the DHD dial'
      InfoSign1: '&6Pour composer, utilisez le clavier du milieu'
      InfoSign2: '&6Utilisez le bouton rouge pour activer'
      InfoSign3: '&6Porte créée par les anciens'
      GateLocked: 'PORTE VERROUILLÉ'
      QuickDial: 'QuickDial'
      
  EditAllGatesGUI:
    GUIName: '&5EditGateListGUI'
    Items:
      Save: '&6Sauvegarder la liste des portails'
      Load: '&6Charger la liste des portes'
      Repair: '&6Réparer TOUS les portails'
      Remove_Armorstands:
        Name: '&6Supprimer toutes les portes'
        Lore: 'Ne retire que les ArmorStand'
      Clear_Gate_List:
        Name: '&6Effacer la liste des portes'
        Lore1: 'Enleve les ArmorStands'
        Lore2: 'et supprime la porte du réseau'
      Cut_all_gate_connections: '&6Couper toutes les connexions de porte'

  EditGateGUI:
    GUIName: '&5EditGateGUI &3{ADDRESS}'
    Items:
      Unlock: '&6Dévérrouiller'
      Lock: '&6Vérrouiller'
      Repair: '&6Réparation de la porte'
      Remove_Event_Horizon:
        Name: '&6RemoveEventHorizon'
        Lore1: 'Enleve les Amor stands'
        Lore2: 'et coupe la connexions'
      Remove_Ring:
        Name: '&6RemoveRing'
        Lore: 'Enleve les Armor stands'
      Remove_Gate:
        Name: '&6Supprimer La Porte'
        Lore1: 'Enleve les ArmorStands'
        Lore2: 'et supprime la porte du réseau'
      Remove_DHD:
        Name: '&6Supprimer DHD'
        Lore: 'Supprime le DHD de la porte'
      Teleport_to_Gate: '&6Téléport à la porte'
      Open: '&6Publique'
      Private: '&6Privée'
      Secundary_Network: '&6Réseau secondaire'
      Gate_Material: '&6Matériaux du portail'
      Reset_Material: '&6Rétablir les matériaux par défaut'
      Set_Gate_Material: '&6Appliquer'
      Ring_Material: '&6Matériau de l anneau'
      Chevron_tip: '&6Chevron Interne'
      Chevron_frame: '&6Contour du chevron'
      Chevron_Light_off: '&6Chevron éteint'
      Chevron_Light_on: '&6Chevron allumer'
      Horizon_Material: '&6Matériel Horizon'
      AddCoOwner:
        Name: '&6Ajouter un copropriétaire'
      ListCoOwner:
        Name: '&6Supprimer un copropriétaire'
      GateOwner:
        Name: '&6Createur de la porte: {OWNER_NAME}'
  
  GateCrystalGUI:
    GUIName: '&5GateCrystalGUI '
    Items:
      DHDCrystal:
        Name: '&5DHDCrystal'
        Lore: '&6AdresseDuPortail:'
  
  NetworkAssignGUI:
    Primary: 'MainNetwork'
    Secundary: 'SecoundNetwork'
    GUIName: '&5{NETNAME}_AssingGUI'
    Items:
      Network: 'Reseau:'
      Next_Page: 'Page Suivante'
      Previous_Page: 'Page Précédente'
   
  QuickDialGUI:
    GUIName: '&5QuickDialGUI'
    Items:
      GateObjects:
        Lore: 
          - 'Nom: {GATENAME}'
          - 'Monde: {WORLD}'
          - 'Localisation: '
          - 'X: {X}'
          - 'Y: {Y}'
          - 'Z: {Z}'
          - 'Res: {NETWORK}'
          - 'Créateur: {OWNER}'
          - '{DESCRIPTION}'
      NextPage: 'Page Suivante'
      PreviousPage: 'Page Précédente'      
    
  GateTools:
    GUIName: '&5GateToolsGUI'
    Items:
      CreateTool:
        Name: '&5GateCreator_Tool'
        Lore: '&fCréer Une Porte'
      EditTool:
        Name: '&5GateEditor_Tool'
        Lore: '&fModifier Une Porte'
      AbydosCartouche:
        Name: '&5Abydos Cartouche'
        Lore: '&fListe De Toute Les Portes Publique'
  
  AddCoOwner:
    GUIName: '&5Ajouter un copropriétaire: {ADDRESS}'
    Items:
      NextPage: 'Page Suivante'
      PreviousPage: 'Page Précédente'
      BackToEditGUI: 'Retour'
      Info: 
        Name: 'Info'
        Text: '&6En cliquant sur la tête d un joueur, il sera ajouté à la liste des copropriétaires.'
  
  RemoveCoOwner:
    GUIName: '&5Supprimer un copropriétaire: {ADDRESS}'
    Items:
      NextPage: 'Page Suivante'
      PreviousPage: 'Page Précédente'
      BackToEditGUI: 'Retour'
      Info: 
        Name: 'Info'
        Text: '&6En cliquant sur la tête d un joueur, il sera retiré de la liste des copropriétaires.'
        
  SetGateOwner:
    GUIName: '&5Createur: {ADDRESS}'
    Items:
      NextPage: 'Page Suivante'
      PreviousPage: 'Page Précédente'
      BackToEditGUI: 'Retour'
      Info: 
        Name: 'Info'
        Text: '&6En cliquant sur la tête d un joueur, il devient le propriétaire de la Porte et vous celui du (des) copropriétaire(s).'
       
PlayerMessages:
  FromGUI:
    AddressAssignGUI:
      Message1: '&f&l[&6&lStargate&f&l] : &2Porte Crée!'
      Message2: '&f&l[&6&lStargate&f&l] : &6Utiliser le cristal pour relier &9la porte &6à un &cDHD'
      Message3: '&f&l[&6&lStargate&f&l] : &cNOTE : &fSi vous voulez déplacer le &cDHD, &f utilisez le &cGateCreate_Tool &f près d une Porte pour récupérer son cristal.'
      Message4: '&f&l[&6&lStargate&f&l] : &cNOTE : &f Les portes peuvent être &c supprimées &f en utilisant le gui de l éditeur &6.'
    
    DHD_GUI:
      Message1: '&f&l[&6&lStargate&f&l] : &cCe portail est réglé sur [Privé].'
      Message2: '&f&l[&6&lStargate&f&l] : &6Pour activer le portail, utilisez les boutons situés au milieu de l écran. Chaque bouton verrouille un symbole spécifique pour l adresse de destination.'
      Message3: '&f&l[&6&lStargate&f&l] : &6L adresse de la porte, &c que vous utilisez actuellement, &6 est affichée dans le nom de l interface graphique du DHD'
      Message4: '&f&l[&6&lStargate&f&l] : &6La porte ne peut être activée seulement si &les 7 symboles d appel&6 de la porte de destination ont été verrouillés.'
      Message5: '&f&l[&6&lStargate&f&l] : &6Les Anciens étaient une puissante race de constructeurs de portes. Peut-être reviendront-ils un jour.'
      Message6: '&f&l[&6&lStargate&f&l] : &cVous ne pouvez pas composer votre propre numéro !'
      Message7: '&f&l[&6&lStargate&f&l] : &cAdresse [{ADDRESS}] introuvable !'
      Message8: '&f&l[&6&lStargate&f&l] : &6La connexion a été annulée'
      Message9: '&f&l[&6&lStargate&f&l] : &cLa connexion n a pas pu être annulée'
      Message10: '&f&l[&6&lStargate&f&l] : &cCe portail est réglé sur [Privé].'
      Message11: '&f&l[&6&lStargate&f&l] : &cLe portail que vous essayez de composer est actuellement indisponible !'
      Message12: '&f&l[&6&lStargate&f&l] : &cLes Portes ne sont pas dans le même réseau !'
      
    EditAllGatesGUI:
      Message1: '&f&l[&6&lStargate&f&l] : La liste des portes a été chargée !'
      Message2: '&f&l[&6&lStargate&f&l] : Porte : &6{ADDRESS}&f a été réparé'
      Message3: '&f&l[&6&lStargate&f&l] : Toutes les portes ont été supprimées !'
      Message4: '&f&l[&6&lStargate&f&l] : Ils peuvent être réparés en utilisant &6 Repair Gate &f dans l EditGateGUI ou &6Repair all Gates &f dans l EditGateListGUI'    
      Message5: '&f&l[&6&lStargate&f&l] : Toutes les connexions entre les Portes ont été coupées !'
      Message6: '&f&l[&6&lStargate&f&l] : Toutes les portes ont été retirées du cartouche &6d Abydos !'
      Message7: '&f&l[&6&lStargate&f&l] : La liste des portails a été sauvegardée !'
      
    EditGateGUI:
      Message1: '&f&l[&6&lStargate&f&l] : &cLa porte sélectionnée n a pas été trouvée !'
      Message2: '&f&l[&6&lStargate&f&l] : Porte : &6{ADDRESS}&f a été déverrouillée'
      Message3: '&f&l[&6&lStargate&f&l] : Porte : &6{ADDRESS}&f a été verrouillée'
      Message4: '&f&l[&6&lStargate&f&l] : Porte : &6{ADDRESS}&f a été réparé'
      Message5: '&f&l[&6&lStargate&f&l] : Porte : &6{ADDRESS}&f a été supprimée. Il peut être réparé en utilisant &6Repair Gate&f dans l EditGateGUI ou &6Repair all Gates &f dans l EditGateListGUI'  
      Message6: '&f&l[&6&lStargate&f&l] : Porte : &6{ADDRESS}&f a été retiré du réseau'
      Message7: '&f&l[&6&lStargate&f&l] : Porte : &6{ADDRESS}&f a été réglé sur [Privé]'
      Message8: '&f&l[&6&lStargate&f&l] : Porte : &6{ADDRESS}&f a été réglé sur [Publique]'
      Message9: '&f&l[&6&lStargate&f&l] : Porte : &6{ADDRESS}&f a été mis à jour avec les nouveau matériaux'
      Message10: '&f&l[&6&lStargate&f&l] :&2DHD a été supprimé.'
     
    QuickDialGUI:
      Message1: '&f&l[&6&lStargate&f&l] : &cAdresse [{ADDRESS}] introuvable !'
      Message2: '&f&l[&6&lStargate&f&l] : &cCe portail est réglé sur [Privé].'
      Message3: '&f&l[&6&lStargate&f&l] : &cCette porte est actuellement active ou compose un autre numéro'
      Message4: '&f&l[&6&lStargate&f&l] : &cLes Gates ne sont pas dans le même réseau'
    
    AddCoOwner:
      Message1: '&f&l[&6&lStargate&f&l] : &2Vous avez été ajouté comme copropriétaire de la porte : &6{ADDRESS}'
      Message2: '&f&l[&6&lStargate&f&l] : &2Vous avez ajouté &6{PLAYER_NAME} &2comme copropriétaire'
    
    RemoveCoOwner:
      Message1: '&f&l[&6&lStargate&f&l] : &cVous avez été retiré des copropriétaires de la porte : &6{ADDRESS}'
      Message2: '&f&l[&6&lStargate&f&l] : &2Vous avez supprimé &b{PLAYER_NAME} &2des copropriétaires'
    
    SetOwner:
      Message1: '&f&l[&6&lStargate&f&l] : &6Vous êtes maintenant le propriétaire de la Porte : &2{ADDRESS}'
      Message2: '&f&l[&6&lStargate&f&l] : &cVous n êtes plus propriétaire de la porte : &6{ADDRESS}'
      Message3: '&f&l[&6&lStargate&f&l] : &cPlayer a déjà atteint la limite des Porte possédés !'
      
  GlobalText:
    DHDBreak: '&f&l[&6&lStargate&f&l] : &cDéconnectez d abord le DHD avant de le casser !'
    NoGateWithAddress: '&f&l[&6&lStargate&f&l] : &cPas de Porte avec l adresse &9{ADDRESS}&c a été trouvé !'
    DescriptionSet: '&f&l[&6&lStargate&f&l] : La description de &2Gate a été établie !'
    GateNameSet: '&f&l[&6&lStargate&f&l] : Le nom de &2Gate a changé !'
    ToManyChars: '&f&l[&6&lStargate&f&l] : &cLe texte donné est trop long ! Seuls {CHAR_AMMOUNT} caractères autorisés !'
    MissingArguments: '&f&l[&6&lStargate&f&l] : &cCertains arguments manquent !'
    NoPermission: '&f&l[&6&lStargate&f&l] : &cVous n avez pas la permission d utiliser cette commande !'
    NoOwnership: '&f&l[&6&lStargate&f&l] : &cVous manquez d appropriation'
    ConfigReload: '&f&l[&6&lStargate&f&l] : Config rechargée !'
    GateNear: '&f&l[&6&lStargate&f&l] : &cIl y a déjà une autre porte à proximité !'
    GateAmmountCap: '&f&l[&6&lStargate&f&l] : Vous ne pouvez plus placer de portes !'
    LinkGate: '&f&l[&6&lStargate&f&l] : &6 Porte : &9{ADDRESS}&6 a été relié au DHD'
    GateNotFound: '&f&l[&6&lStargate&f&l] : &cLa Porte &6{ADDRESS}&c n est plus dans&6 le Cartouche d Abydos'
    WrongDHDMaterial: '&f&l[&6&lStargate&f&l] : &cLe crystal&c ne peut être utilisé que sur un &6'
    NoGatesNearBy: '&f&l[&6&lStargate&f&l] : &cIl n y a pas de portail à proximité !'
    GateAllreadyInDatabase: '&f&l[&6&lStargate&f&l] : &c La porte avec l adresse : &6{ADDRESS}&c existe déjà dans la base de données mais n a pas encore été synchronisée avec le serveur !'
    